title = "J Slowen Music"
baseURL = "https://jslowen-music.netlify.app"
languageCode = "en-us"
theme = "github.com/theNewDynamic/gohugo-theme-ananke"
themesDir = "../.."
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-1284818-10"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "J Slowen Music"
    weight = 1
    contentDir = "exampleSite/content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "/images/favicon.ico"
  site_logo = "/images/Logo1x_white.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/keys_1920.jpg"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "soundcloud"
  url = "https://www.soundcloud.com/jslowenmusic"
  label = "soundcloud"
  color = "#ff7700"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/jslowenmusic"
[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/jslowenmusic"

[[menu.main]]
  URL = "/about"
  name = "About"
  weight = 1
[[menu.main]]
  URL = "/music"
  name = "Music"
  weight = 2
[[menu.main]]
  URL = "/contact"
  name = "Contact"
  weight = 3
